name: 'Start Ethereum Test Node'
description: 'GitHub Action to setup an Ethereum node to test Smart Contracts'
author: 'AgustinSRG'
branding:
  icon: 'database'
  color: 'green'
inputs:
  rpcPort:
    description: 'The RPC port'
    required: false
    default: '8545'
  websocket:
    description: 'Set to ON in order to enable WebSockets'
    required: false
    default: 'OFF'
  websocketPort:
    description: 'The WebSockets port'
    required: false
    default: '8546'
runs:
  using: 'docker'
  image: 'Dockerfile'
