name: 'Start Ethereum Test Node'
description: 'GitHub Action to setup an Ethereum node to test Smart Contracts'
author: 'AgustinSRG'
branding:
  icon: 'database'
  color: 'green'
inputs:
  rpcPort:
    description: 'The RPC port'
    required: false
    default: '8545'
runs:
  using: 'docker'
  image: 'Dockerfile'
